[build]
  # 빌드 명령어
  command = "npm run build"
  
  # 빌드 결과물 디렉토리
  publish = ".next"
  
  # Node.js 버전 지정
  environment = { NODE_VERSION = "18" }

[build.environment]
  # 빌드 시 환경 변수
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# Next.js 라우팅을 위한 리다이렉트 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API 라우트 처리
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 보안 헤더 설정
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 캐시 설정
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
