export type SpriteMetadata = {
  src: string;
  pixelDensity: number;
  tags?: string[];
  notes?: string;
};

/**
 * Central registry for pixel sprites. Entries will be generated by the sprite sync script.
 * Until the pipeline is in place, keep manual entries minimal and document sources in the UI reference folder.
 */
export const SPRITE_REGISTRY: Record<string, SpriteMetadata> = {
  "facility-solar": {
    src: "/assets/sprites/solar-array.svg",
    pixelDensity: 64,
    tags: ["facility", "energy", "solar"],
    notes: "Primary renewable energy generator",
  },
  "facility-wind": {
    src: "/assets/sprites/wind-turbine.svg",
    pixelDensity: 64,
    tags: ["facility", "energy", "wind"],
    notes: "High output wind turbine",
  },
  "facility-residential": {
    src: "/assets/sprites/residential-block.svg",
    pixelDensity: 64,
    tags: ["facility", "housing"],
    notes: "Eco-friendly residential complex",
  },
  "facility-park": {
    src: "/assets/sprites/city-park.svg",
    pixelDensity: 64,
    tags: ["facility", "civic", "park"],
    notes: "Urban green space",
  },
  "facility-recycling": {
    src: "/assets/sprites/recycling-center.svg",
    pixelDensity: 64,
    tags: ["facility", "circular"],
    notes: "Waste to resource hub",
  },
};

export function getSpriteMetadata(spriteId: string) {
  return SPRITE_REGISTRY[spriteId];
}
